### ISSUE TITLE
Error: EPERM: operation not permitted, scandir

### ISSUE THREAD

**Issue by MitchellJeppson** [richinfante/iphonebackuptools#48]
I just downloaded the tool using `npm i -g ibackuptool` 

When I run `sudo ibackuptool -l`, I receive the following error:

    run backups.list
    [cli.js] unhandled rejection { Error: EPERM: operation not permitted, scandir     '/Users/mitchelljeppson/Library/Application Support/MobileSync/Backup/'
        at Object.readdirSync (fs.js:786:3)
        at Promise (/usr/local/lib/node_modules/ibackuptool/tools/reports/backups/list.js:10:22)
        at new Promise (<anonymous>)
        at Object.run (/usr/local/lib/node_modules/ibackuptool/tools/reports/backups/list.js:9:12)
        at Promise (/usr/local/lib/node_modules/ibackuptool/tools/index.js:182:12)
        at new Promise (<anonymous>)
        at Object.runReport (/usr/local/lib/node_modules/ibackuptool/tools/index.js:159:10)
        at main (/usr/local/lib/node_modules/ibackuptool/tools/cli.js:196:37)
        at init (/usr/local/lib/node_modules/ibackuptool/tools/cli.js:136:3)
        at Object.<anonymous> (/usr/local/lib/node_modules/ibackuptool/tools/cli.js:91:3)
      errno: -1,
      syscall: 'scandir',
      code: 'EPERM',
      path:
      '/Users/mitchelljeppson/Library/Application Support/MobileSync/Backup/' }

Any thoughts on this? Thanks.

**Comment by mediter** [comment]
Could it be caused by the enhanced security in the latest macOS Catalina beta?

**Comment by MitchellJeppson** [comment]
No, I am still running macOS Mojave.

**Comment by richinfante** [comment]
Hmm interesting, I've never encountered this before. If you're able to, could you run the following command to get the permissions for that directory and share the output?:
```bash
ls -la ~/Library/Application\ Support/MobileSync/
```

**Comment by MitchellJeppson** [comment]
I get `ls: : Operation not permitted`, even if I run it with sudo. I can `ls` into other directories in the Application Support directory, but not MobileSync. Permissions and owner look fine. Any other ideas?

**Comment by richinfante** [comment]
Out of curiosity, have you tried this? It might just be that your terminal app needs some extra permissions for this directory:

**Comment by MitchellJeppson** [comment]
That fixed it for me. Thanks!
