### ISSUE TITLE
trying to run on windows 10 but got The "path" argument must be of type string

### ISSUE THREAD

**Issue by poshih** [richinfante/iphonebackuptools#60]
installed using
npm i -g ibackuptool

when run ibackuptool with any arg this error happens

ibackuptool -l
internal/validators.js:118
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:118:11)
    at Object.join (path.js:375:7)
    at Object.<anonymous> (C:\Users\secre\AppData\Roaming\npm\node_modules\ibackuptool\tools\index.js:9:28)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\secre\AppData\Roaming\npm\node_modules\ibackuptool\tools\cli.js:9:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by poshih** [comment]
I edited the var backupDirectory = to the dir I want
