### ISSUE TITLE
ERROR: Couldn't run 'backup.files'.

### ISSUE THREAD

**Issue by eciftcioglu** [richinfante/iphonebackuptools#88]
I am getting the current output as an error on the terminal. 

Couldn't run 'backup.files'.
ERROR! Error: Could not find a manifest.
    at /opt/homebrew/lib/node_modules/ibackuptool/tools/reports/backup/files.js:94:12

**Comment by idsphilipmears** [comment]
I am getting the same error on an Ubuntu terminal:

```
run backup.files
ERROR! Couldn't run 'backup.files'.
ERROR! Error: Could not find a manifest.
    at /usr/local/lib/node_modules/ibackuptool/tools/reports/backup/files.js:94:12
[cli.js] unhandled rejection TypeError: rows is not iterable
    at /usr/local/lib/node_modules/ibackuptool/tools/reports/backup/files.js:50:27
    at Statement.errBack (/usr/local/lib/node_modules/ibackuptool/node_modules/sqlite3/lib/sqlite3.js:14:21)

```
